apiVersion: arubacloud.com/v1alpha1
kind: CloudServer
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - sample-tag
  location:
    value: ITBG-Bergamo
  dataCenter: ITBG-1
  vpcReference:
    name: __NAME__
    namespace: default
  vpcPreset: False
  flavorName: CSO4A8
  subnetReferences:
    - name: __NAME__
      namespace: default
  elasticIpReference:
    name: __NAME__
    namespace: default
  securityGroupReferences:
    - name: __NAME__
      namespace: default
  keyPairReference:
    name: __NAME__
    namespace: default
  bootVolumeReference:
    name: __NAME__
    namespace: default
  projectReference:
    name: __NAME__
    namespace: default
