apiVersion: arubacloud.com/v1alpha1
kind: CloudServer
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tags:
    - e2e-test
  location:
    value: ITBG-Bergamo
  dataCenter: ITBG-1
  vpcReference:
    name: __NAME__
    namespace: __NAMESPACE__
  vpcPreset: false
  flavorName: CSO4A8
  subnetReferences:
    - name: __NAME__
      namespace: __NAMESPACE__
  securityGroupReferences:
    - name: __NAME__
      namespace: __NAMESPACE__
  keyPairReference:
    name: __NAME__
    namespace: __NAMESPACE__
  bootVolumeReference:
    name: __NAME__
    namespace: __NAMESPACE__
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
