apiVersion: arubacloud.com/v1alpha1
kind: Vpc
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - tag-4
    - tag-3
  location:
    value: ITBG-Bergamo
  projectReference:
    name: __NAME__
    namespace: default
properties:
  preset: false
  default: false
