apiVersion: arubacloud.com/v1alpha1
kind: Subnet
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - tag-1
    - tag-2
  type: Advanced
  default: false
  network:
    address: 192.168.1.0/25
  dhcp:
    enabled: true
  vpcReference:
    name: __NAME__
    namespace: default
  projectReference:
    name: __NAME__
    namespace: default
