apiVersion: arubacloud.com/v1alpha1
kind: BlockStorage
metadata:
  name: __NAME__-data
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - tag-1
  location:
    value: ITBG-Bergamo
  sizeGb: 40
  billingPeriod: Hour
  dataCenter: ITBG-1
  bootable: false
  projectReference:
    name: __NAME__
    namespace: default
