apiVersion: arubacloud.com/v1alpha1
kind: ElasticIp
metadata:
  name: __NAME__04
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - sample
    - elastic-ip
    - test
  location:
    value: ITBG-Bergamo
  billingPlan:
    billingPeriod: Hour
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
