apiVersion: arubacloud.com/v1alpha1
kind: SecurityRule
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - tag-1
    - tag-2
  location:
    value: ITBG-Bergamo
  protocol: TCP
  port: '80-90'
  direction: Egress
  target:
    kind: Ip
    value: '0.0.0.0/0'
  securityGroupReference:
    name: __NAME__
    namespace: default
  vpcReference:
    name: __NAME__
    namespace: default
  projectReference:
    name: __NAME__
    namespace: default
