apiVersion: arubacloud.com/v1alpha1
kind: SecurityGroup
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tenant: __TENANT__
  tags:
    - tag-1
    - tag-2
  location:
    value: ITBG-Bergamo
  default: false
  vpcReference:
    name: __NAME__
    namespace: __NAMESPACE__
  projectReference:
    name: __NAME__
    namespace: __NAMESPACE__
