apiVersion: arubacloud.com/v1alpha1
kind: Subnet
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tags:
    - e2e-test
  location:
    value: ITBG-Bergamo
  vpcReference:
    name: __VPC_NAME__
    namespace: __VPC_NAMESPACE__
  projectReference:
    name: __PROJECT_NAME__
    namespace: __PROJECT_NAMESPACE__
