apiVersion: arubacloud.com/v1alpha1
kind: CloudServer
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tags:
    - e2e-test
    - full-stack
  location:
    value: ITBG-Bergamo
  dataCenter: ITBG-1
  vpcReference:
    name: __VPC_NAME__
    namespace: __VPC_NAMESPACE__
  vpcPreset: false
  flavorName: CSO4A8
  subnetReferences:
    - name: __SUBNET_NAME__
      namespace: __SUBNET_NAMESPACE__
  elasticIpReference:
    name: __ELASTICIP_NAME__
    namespace: __ELASTICIP_NAMESPACE__
  securityGroupReferences:
    - name: __SG_NAME__
      namespace: __SG_NAMESPACE__
  keyPairReference:
    name: __KEYPAIR_NAME__
    namespace: __KEYPAIR_NAMESPACE__
  bootVolumeReference:
    name: __BOOT_VOLUME_NAME__
    namespace: __BOOT_VOLUME_NAMESPACE__
  dataVolumeReferences:
    - name: __DATA_VOLUME_NAME__
      namespace: __DATA_VOLUME_NAMESPACE__
  projectReference:
    name: __PROJECT_NAME__
    namespace: __PROJECT_NAMESPACE__
