apiVersion: arubacloud.com/v1alpha1
kind: BlockStorage
metadata:
  name: __NAME__
  namespace: __NAMESPACE__
spec:
  tags:
    - e2e-test
    - boot-disk
  location:
    value: ITBG-Bergamo
  sizeGb: 40
  billingPeriod: Hour
  dataCenter: ITBG-1
  bootable: true
  image: LU20-001
  projectReference:
    name: __PROJECT_NAME__
    namespace: __PROJECT_NAMESPACE__
