apiVersion: arubacloud.com/v1alpha1
kind: Project
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  description: Test project for local development
  tags:
    - test-ciao
    - local
  default: false
